import { useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { LogIn, UserPlus, ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export default function AuthPage(){
 const {signIn,signUp,configured}=useAuth(); const nav=useNavigate(); const loc=useLocation();
 const [mode,setMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const r=mode==='login'?await signIn(email,password):await signUp(email,password,name);setBusy(false);if(r.error)setError(r.error);else if(mode==='signup')setError('Cuenta creada. Revisa tu correo si Supabase tiene confirmación de email activada.');else nav((loc.state as any)?.from||'/dashboard')}
 if(!configured)return <div className="grid min-h-screen place-items-center bg-slate-950 p-5"><div className="max-w-lg rounded-[2rem] bg-white p-8 text-center"><div className="text-4xl">🧭</div><h1 className="mt-3 text-2xl font-black">DataQuest está en modo demo</h1><p className="mt-3 text-sm leading-6 text-slate-500">Para activar cuentas reales, sincronización entre dispositivos, ranking y panel admin, configura Supabase con las variables <b>VITE_SUPABASE_URL</b> y <b>VITE_SUPABASE_PUBLISHABLE_KEY</b>.</p><Link to="/dashboard" className="mt-6 inline-flex rounded-2xl bg-indigo-600 px-5 py-3 text-sm font-extrabold text-white">Continuar con demo</Link></div></div>;
 return <div className="grid min-h-screen place-items-center bg-slate-950 p-5"><div className="w-full max-w-md rounded-[2rem] bg-white p-7 shadow-2xl"><Link to="/" className="font-black">🧭 DataQuest</Link><h1 className="mt-8 text-3xl font-black">{mode==='login'?'Bienvenido de nuevo':'Crea tu cuenta'}</h1><p className="mt-2 text-sm text-slate-500">Tu progreso vive en la nube y se sincroniza entre dispositivos.</p><form onSubmit={submit} className="mt-7 space-y-3">{mode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Nombre" className="w-full rounded-2xl border p-3 text-sm"/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="Email" className="w-full rounded-2xl border p-3 text-sm"/><input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Contraseña (mín. 6 caracteres)" className="w-full rounded-2xl border p-3 text-sm"/>{error&&<div className="rounded-2xl bg-amber-50 p-3 text-xs font-bold text-amber-800">{error}</div>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-600 py-3 font-extrabold text-white disabled:opacity-50">{mode==='login'?<LogIn size={17}/>:<UserPlus size={17}/>} {busy?'Procesando…':mode==='login'?'Entrar':'Crear cuenta'}</button></form><button onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}} className="mt-4 w-full text-sm font-bold text-indigo-600">{mode==='login'?'Crear una cuenta':'Ya tengo una cuenta'}</button><div className="mt-6 flex items-center gap-2 rounded-2xl bg-slate-50 p-3 text-xs text-slate-500"><ShieldCheck size={16}/> El acceso se gestiona con Supabase Auth.</div></div></div>
}
