import { useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Flame, LockOpen, Star, Zap } from 'lucide-react';
import { useProgress } from '../context/ProgressContext';

export function ProgressBar({ value }: { value: number }) { return <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-cyan-400 transition-all duration-500" style={{ width: `${Math.min(value, 100)}%` }} /></div>; }
export function XPBadge({ xp }: { xp: number }) { return <span className="pill inline-flex items-center gap-1 text-amber-700"><Zap size={13} className="fill-amber-400 text-amber-500" />+{xp} XP</span>; }
export function StreakCounter({ days }: { days?: number }) { const { streak } = useProgress(); const value = days ?? streak; return <div className="flex items-center gap-2 rounded-2xl bg-orange-50 px-3 py-2 text-orange-700"><Flame size={18} className="fill-orange-400" /><div><div className="text-sm font-extrabold">{value} {value === 1 ? 'día' : 'días'}</div><div className="text-[10px] font-medium opacity-70">racha activa</div></div></div>; }
export function RouteCard({ route, progress=0 }: { route:any; progress?:number }) { return <Link to={`/ruta/${route.id}`} className="tap group block rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className={`grid h-12 w-12 place-items-center rounded-2xl text-2xl ${route.accent==='violet'?'bg-violet-100':route.accent==='sky'?'bg-sky-100':'bg-emerald-100'}`}>{route.icon}</div><span className="pill">{route.levels.length} niveles</span></div><h3 className="mt-5 text-xl font-extrabold">{route.title}</h3><p className="mt-2 min-h-[48px] text-sm leading-6 text-slate-500">{route.short}</p><div className="mt-5 flex items-center justify-between text-xs font-semibold text-slate-500"><span>{route.levels.reduce((a:any,l:any)=>a+l.lessons.length,0)} lecciones</span><span>{progress}%</span></div><div className="mt-2"><ProgressBar value={progress}/></div><div className="mt-5 flex items-center justify-between font-bold text-indigo-600">Explorar ruta <ArrowRight size={17} className="transition group-hover:translate-x-1"/></div></Link>; }
export function LevelCard({ route, level, progress=0 }: { route:any; level:any; progress?:number }) { return <div className="tap rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 inline-flex items-center gap-2 text-xs font-bold text-indigo-600"><LockOpen size={14}/> Disponible desde el inicio</div><h3 className="text-xl font-extrabold">{level.title}</h3><p className="mt-1 text-sm font-medium text-slate-500">{level.subtitle}</p></div><div className="flex gap-1">{[1,2,3,4,5].map(n=><Star key={n} size={14} className={n<=level.difficulty?'fill-amber-400 text-amber-400':'text-slate-200'}/>)}</div></div><p className="mt-4 text-sm leading-6 text-slate-600">{level.description}</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-2xl bg-slate-50 p-3"><b>{level.modules}</b><span className="ml-1 text-slate-500">módulos</span></div><div className="rounded-2xl bg-slate-50 p-3"><b>{level.exercises}</b><span className="ml-1 text-slate-500">ejercicios</span></div></div><div className="mt-4 flex items-center justify-between text-xs font-semibold text-slate-500"><span>Progreso</span><span>{progress}%</span></div><div className="mt-2"><ProgressBar value={progress}/></div><Link to={`/ruta/${route.id}/${level.id}`} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-bold text-white hover:bg-indigo-600">Entrar al nivel <ArrowRight size={16}/></Link></div>; }
export function LessonCard({ lesson, routeId, levelId, index }: { lesson:any; routeId:string; levelId:string; index:number }) { const { isCompleted } = useProgress(); const done = isCompleted(lesson.id); return <Link to={`/leccion/${routeId}/${levelId}/${lesson.id}`} className="tap flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-extrabold ${done?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{done?<Check size={18}/>:index+1}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h4 className="truncate font-bold">{lesson.title}</h4>{done&&<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-700">Hecha</span>}</div><p className="mt-1 text-xs text-slate-500">{lesson.type} · {lesson.duration} min</p></div><XPBadge xp={lesson.xp}/><ArrowRight size={16} className="text-slate-400"/></Link>; }
export function Stat({ icon, label, value }: { icon:ReactNode; label:string; value:string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="mb-3 text-slate-400">{icon}</div><div className="text-xl font-extrabold">{value}</div><div className="mt-1 text-xs font-medium text-slate-500">{label}</div></div>; }
export function AchievementCard({ icon, title, description, done=true }: { icon:string; title:string; description:string; done?:boolean }) { return <div className={`rounded-2xl border p-4 ${done?'border-amber-200 bg-amber-50/60':'border-slate-200 bg-white opacity-60'}`}><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white text-2xl shadow-sm">{icon}</div><div><div className="font-extrabold">{title}</div><div className="text-xs text-slate-500">{description}</div></div></div></div>; }

export function QuizCard({ question, options, correctIndex, lessonId, onResult }: { question:string; options:string[]; correctIndex:number; lessonId:string; onResult?:(correct:boolean, bonus:number)=>void }) {
  const [selected, setSelected] = useState<number | null>(null); const [checked, setChecked] = useState(false); const [correct, setCorrect] = useState(false); const { completeQuiz } = useProgress();
  function check() { if (selected === null || checked) return; const ok = selected === correctIndex; setCorrect(ok); setChecked(true); const result = completeQuiz(lessonId, ok); onResult?.(ok, result.bonus); }
  return <div className="rounded-3xl border border-indigo-100 bg-indigo-50/60 p-5"><div className="text-xs font-extrabold uppercase tracking-wider text-indigo-600">Mini quiz</div><h3 className="mt-2 text-lg font-extrabold">{question}</h3><div className="mt-4 grid gap-2">{options.map((o,i)=><button key={o} disabled={checked} onClick={()=>setSelected(i)} className={`rounded-2xl border p-3 text-left text-sm font-semibold transition ${selected===i?'border-indigo-500 bg-white text-indigo-700':'border-slate-200 bg-white hover:border-indigo-300'} disabled:cursor-default`}>{o}</button>)}</div>{checked&&<div className={`mt-4 rounded-2xl p-3 text-sm font-bold ${correct?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{correct?'¡Correcto! +5 XP de bonus.':'No pasa nada, vuelve a intentarlo. El resultado del quiz ya quedó registrado.'}</div>}<button disabled={selected===null||checked} onClick={check} className="mt-4 w-full rounded-2xl bg-indigo-600 py-3 text-sm font-bold text-white disabled:opacity-40">Comprobar respuesta</button></div>; }
