import { Routes,Route,Navigate,useLocation } from 'react-router-dom';
import type { ReactNode } from 'react';
import { AuthProvider,useAuth } from './context/AuthContext';
import { ContentProvider } from './context/ContentContext';
import { ProgressProvider } from './context/ProgressContext';
import Layout from './components/Layout';
import Landing from './pages/Landing';import Dashboard from './pages/Dashboard';import RoutesPage from './pages/RoutesPage';import RouteDetail from './pages/RouteDetail';import LevelPage from './pages/LevelPage';import LessonPage from './pages/LessonPage';import Profile from './pages/Profile';import Achievements from './pages/Achievements';import AuthPage from './pages/AuthPage';import Ranking from './pages/Ranking';import Admin from './pages/Admin';
function RequireAuth({children}:{children:ReactNode}){const{user,loading,configured}=useAuth();const loc=useLocation();if(!configured)return <>{children}</>;if(loading)return <div className="grid min-h-screen place-items-center text-sm font-bold text-slate-500">Cargando DataQuest…</div>;return user?children:<Navigate to="/login" replace state={{from:loc.pathname}}/>}
function RequireAdmin({children}:{children:ReactNode}){const{profile,loading}=useAuth();if(loading)return <div className="grid min-h-screen place-items-center">Cargando…</div>;return profile?.role==='admin'?children:<Navigate to="/dashboard" replace/>}
export default function App(){return <AuthProvider><ContentProvider><ProgressProvider><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<AuthPage/>}/><Route element={<RequireAuth><Layout/></RequireAuth>}><Route path="/dashboard" element={<Dashboard/>}/><Route path="/rutas" element={<RoutesPage/>}/><Route path="/ruta/:routeId" element={<RouteDetail/>}/><Route path="/ruta/:routeId/:levelId" element={<LevelPage/>}/><Route path="/leccion/:routeId/:levelId/:lessonId" element={<LessonPage/>}/><Route path="/perfil" element={<Profile/>}/><Route path="/logros" element={<Achievements/>}/><Route path="/progreso" element={<Dashboard/>}/><Route path="/ranking" element={<Ranking/>}/><Route path="/admin" element={<RequireAdmin><Admin/></RequireAdmin>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></ProgressProvider></ContentProvider></AuthProvider>}
